### ISSUE TITLE
Chatlist is not updated when coming back to the app

### ISSUE THREAD

**Issue by dignifiedquire** [deltachat/deltachat-ios#1079]
Can be easily seen when sending a message, it only gets updated if I wait for a while? and when going into a chat and coming back.

**Comment by cyBerta** [comment]
I'm not sure if I understand the issue here. How do you send a message without being in chat? Do you mean by using the share extension from another app and returning to DC while the chat list is visible? I just tested that scenario and it updates fine.
And when sending a message from a chat and returning to the chat list, the UI is updated as you said. Could you explain, under which conditions you can reproduce that bug?

**Comment by dignifiedquire** [comment]
example: message was sent 1min ago, I leave the app for 2min and come back. the chatlist still shows sent 1min ago but if I go into the chat it says 3min ago, hoing back the chatlist is now updated

**Comment by cyBerta** [comment]
that clarifys it, thanks!
