### ISSUE TITLE
Nothing happens when writing a message

### ISSUE THREAD

**Issue by fschulze** [deltachat/deltachat-ios#11]
I'm testing Delta Chat on my iPad. When I added a contact and sent a message nothing seems to happen. I don't see my own message in Delta Chat and I don't see any change in my IMAP account or the destination account. I'm using fastmail.com.

**Comment by jonasreinsch** [comment]
@fschulze ok, thank you - could you try the following: delete the app, reinstall and re-enter the IMAP credentials. We added a little bit of error reporting in the 3rd beta - does the configuration succeed or is there an error message displayed?

**Comment by fschulze** [comment]
```
Warning
Configuration failed. Make sure to
enter correct credentials. If using
GMail, enable access for 'less secure
apps' first.
```

What exactly does it need? I created an IMAP/POP/SMTP application password in fastmail.
The progress bar seems to have about 5 steps and it failed on the 4th or last afaict.

**Comment by jonasreinsch** [comment]
@fschulze thanks for reporting

@r10s ok, probably we need this todo item then first 'allow advanced configuration options on setup to make sure users can connect if the autoconfig fails (imap-server, imap-port, imap-flags, same for smtp - if not yet implemented (cannot test currently, iphone-battery is empty))', right? Or should the automatic configuration work / does it work in Android for fastmail?

**Comment by fschulze** [comment]
I don't have Android to test.

Shouldn't the auto-configuration information be available anonymously, without requiring a fastmail account?

I can probably look and test in more detail on friday.

**Comment by r10s** [comment]
i also do not use fastmail, however, the provider overview at https://support.delta.chat/t/provider-overview/56/2 says that it is needed to create an "create app-specific-password" and login with that.

**Comment by jonasreinsch** [comment]
@r10s ah, thanks for that. Do you link to this list from within the Android app upon config failure?

**Comment by fschulze** [comment]
@r10s I did create an app specific password with imap/pop/smtp permissions, or do you mean the app needs to do something with it which is currently missing?

**Comment by r10s** [comment]
@jonasreinsch no, but this might be an idea in the future, however, for now, the list is not "complete" enough imho (it's rather new)

however, what i do on android is to "catch" DC_EVENT_ERROR messages during configuration and show them in a separate dialog after dc_configure() has failed. (in generall, all DC_EVENT_ERROR messages should be shown to the user in a non-disturbing way; for android i do this with a bubble/toast, not sure how this works on ios).

normally, the DC_EVENT_ERROR message reports more details about the problem, btw. eg. server-messages are shown there.

**Comment by r10s** [comment]
@fschulze yes, i think this is what is suggested in the provider overview.
_normally_ this could be used as the credentials in delta chat then.

**Comment by jonasreinsch** [comment]
@r10s ok, but generally DC_EVENT_ERROR can also happen outside confguration, right (just for clarification)? Do you also show DC_EVENT_WARNING/DC_EVENT_INFO to the user?

Currently, we *detect* failed configuration via checking if DC_EVENT_CONFIGURE_PROGRESS reports a progress of zero - is that exhaustive or are there other possibilities for configuration to fail?

**Comment by r10s** [comment]
@jonasreinsch i show only DC_EVENT_ERROR to the user, normally in a non-disturbing bubble (errors are typically sth. as "No network - cannot send".
DC_EVENT_WARNING/DC_EVENT_INFO should not be shown to the user but logged so that the user/dev can access them as needed.

i think, for the beginning, this bubble is also sufficient during configuration, however, i found it more convenient to have the message in a dialog there, so, for android, i handle this differently during dc_configure() (just by a flag in android-land, there is nothing in the core that helps you there)

@fschulze wrt fastmail: i just tried it out in my cli-test environment, and it works. without an app-specific password, delta reports the following text by DC_EVENT_ERROR: `
Cannot login as timhans4@fastmail.com. Response from imap.fastmail.com: Sorry, you need to create an app password to use this service. See our help for more details.` after setting up an app-specific password, the login succeeds and i can send and receive messages.
the configuration is done via autoconfig btw, delta loads https://autoconfig.fastmail.com/mail/config-v1.1.xml?emailaddress=timhans4%40fastmail.com and uses the info from there.
iiuc, only the brand-new ios-version supports this.

**Comment by jonasreinsch** [comment]
The last message from DC_EVENT_ERROR is now displayed if the configuration fails (like recommended here: https://deltachat.github.io/api/group__DC__EVENT.html#gaf7b3f4a361fc9515a79758bd49a376d0 )

**Comment by r10s** [comment]
great :)

**Comment by fschulze** [comment]
```
Warning
Could not connect to IMAP-server
imap.fastmail.fm:993 using SSL. (Error
#6)
```

**Comment by jonasreinsch** [comment]
I have to implement fully customizable settings anyway, so I probably will do that next (but won't have much time before the weekend). @r10s is there a way to get a detailed step-by-step error log from the core like @fschulze suggested?

**Comment by r10s** [comment]
currently, there is only the percentage.
however, when things fail and the last error received is printed, you should get an idea about what is going wrong.

**Comment by r10s** [comment]
wrt showing error messages, i filed another issue as this one goes off-topic here, #12, it's not urgent anyway and maybe there is nothing to do :)

@jonasreinsch i'm also in freiburg beginning of the next week :)

**Comment by jonasreinsch** [comment]
@fschulze a new Testflight build is available now with advanced configuration options - it is not thoroughly tested yet but you could try if you can connect now.

**Comment by fschulze** [comment]
Works now!

**Comment by jonasreinsch** [comment]
thank you for testing again!
