### ISSUE TITLE
let mailto:-links in other apps open Delta Chat

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#1126]
now, that classic email becomes more a thing for Delta Chat, it would be great if Delta Chat opens when the user clicks a `mailto:`-link in other apps, esp. in the browser.

@Hocuri did a testing page for that when the stuff got implemented on android, probably, that is useful for iOS as well:
https://github.com/deltachat/interface/blob/master/user-testing/mailto-links.md

**Comment by r10s** [comment]
this seems possible since iOS 14 only:

<img width=380 src=https://user-images.githubusercontent.com/9800740/113573420-6bfd2380-961a-11eb-82a1-3735ee8d2c21.png>

https://www.apple.com/ios/ios-14/

**Comment by cyBerta** [comment]
https://developer.apple.com/documentation/xcode/preparing-your-app-to-be-the-default-browser-or-email-client

**Comment by cyBerta** [comment]
aand reopend and on top of our list

**Comment by cyBerta** [comment]
I was reading: 
- https://developer.apple.com/documentation/xcode/preparing-your-app-to-be-the-default-browser-or-email-client to check the requirements for a requesting
- https://developer.apple.com/documentation/bundleresources/entitlements for refreshing my understanding of what entitlements are
- https://help.apple.com/developer-account/#/dev38c81d4cd in order to understand better what **_managed_** entitlements are 

and I'm still puzzled if and where I have to manually add `com.apple.developer.mail-client=true` as described [here](https://developer.apple.com/forums/thread/650822) needs to be done manually and BEFORE requesting the entitlement? 
From the `deltachat-ios` target -> signing & capabilities -> + Capabilities there's no way to add that mail-client entitlement.

**Comment by r10s** [comment]
moving stale feature request to resurrection

**Comment by r10s** [comment]
in the light of "chatmail", a mailto: handler would not help as this would not result in encrypted mail; cmp android discussion about getting rid of that https://github.com/deltachat/deltachat-android/issues/3162

so, removing from "resurrection" and closing this issue as "not planned"
