### ISSUE TITLE
Annoying Delta-chat messages appear in the mail app

### ISSUE THREAD

**Issue by havet** [deltachat/deltachat-ios#1144]
- Operating System (Linux/Mac/Windows/iOS/Android):  iOS 14.4.2 on  an iPhone 8
- Delta Chat Version: 1.16.0
- Expected behavior: No interference with ordinary mail
- Actual behavior: Notifications from the e-mail app for DeltaChat message and lots of DeltaChat message when opening the mail app.
- Steps to reproduce the problem: chat a while
- Screenshots: no
- Logs:

This is very annoying for the user! Might get upset and delete the DeltaChat messages. Might force an unistall of DeltaChat to get rid of the problem.

**Comment by r10s** [comment]
the chat-messages should be moved to the DeltaChat folder; alternatively, you can use a dedicated account for Delta Chat - or, in the near future, when email-compatibility gets improved further (see https://github.com/deltachat/deltachat-core-rust/issues/2335 ) maybe only Delta Chat :)

**Comment by Hocuri** [comment]
@r10s did you want to link to https://github.com/orgs/deltachat/projects/31? The issue you linked to is just a very annoying bug (& regression), I only put in into the email-compat project so that there is no risk of forgetting about it when releasing (unlikely, but anyway)

Shall we close this issue here? There is nothing we can do against it apart from further improving the e-mail-compability

**Comment by r10s** [comment]
> @r10s did you want to link to https://github.com/orgs/deltachat/projects/31?

sure, copy+paster error :)

> Shall we close this issue here?

i'd say so, there is nothing ios can do about that at least.

@havet feel free to chime in, we're reading also closed issues, however, we try to keep only issues open with actually actionable items and/or someone is working on :)
