### ISSUE TITLE
Delete from server is global 

### ISSUE THREAD

**Issue by havet** [deltachat/deltachat-ios#1160]
- Operating System (Linux/Mac/Windows/iOS/Android): iOS 14.4.2 (and probably the others as well)
- Delta Chat Version: 1.16.0
- Expected behavior: Delete mail from the Delta Chat folder
- Actual behavior: Deletes all mail from all folders
- Steps to reproduce the problem: In settings, choose "Delete messages from server"

A warning message is displayed, though.
But I don't see any reason to the actual behaviour - is it a bug or a feature? Is the warning message a work around?

Anyhow, the behaviour implies that all users MUST have a dedicated e-mail address for Delta Chat.
If chatting a lot, the mail server will be clotted up with lots of small meaningless e-mails. Deleting old messages will be necessary. 

Deleting only mail in the Delta Chat folder would be safe.
Is there any problem to change the behaviour of Delta Chat to the expected behaviour?

**Comment by r10s** [comment]
the user may have "Show emails" enabled or "Automatic Moves to Delta Chat Folder" disabled. Also the server may move messages around.

So, this option is about to delete all message from the server that is handled by Delta Chat somehow, and this is what the warning is about.

the option does not delete messages that are not "seen" by Delta Chat, so the folders are not just emptied - but depending on the users settings, the result may be similar, therefore we voted for a harsher warning.

maybe the warning can be improved, however, in general, this is the expected behavior, closing this issue therefore.
