### ISSUE TITLE
background image

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#127]
it should be possible to select a background image as in android.

before this can be implemented, however, the message status (time etc.) should go inside the bubble as it is otherwise hard wrt contrast and readability)

**Comment by nayooti** [comment]
Regarding placing the chat details inside the chat bubbles, I believe this isn't as easy as it sounds.

We're using the MessageKit-framework with one of their out-of-the-box examples. It was perfectly fine at the prototype stage back then, since it was very easy to implement. 

Within the last couple months I actually tried to enhance the look&feel of the ChatView a bit since I found this is the view the user spends the most time. But I gave up since it was very time consuming and other new features seemed to be more important back then.

What I can say is that I really struggled making any changes to the out of the box solution. 
Here are a few things I tried and where I failed:

- vertically center align the send/attach button with the message input bar
- in non-group-chats we actually don't need the avatars (one avatar is displayed in the navigation bar), so I thought it would be nice, to hide the avatars in single-chats and put the bubbles a bit further to the left
- on whatsapp/telegram it is common to group messages by day, showing a horizontally centered day-cell as a divider.
- make the distance between messages smaller 

This what I tried two weeks ago and failed too:
- show thumbnails of video-messages 

At one point I tried to use a plain messageKit-controller with the plan to add new features peace-by-peace. I didn't spend too much time on this, but you can find this attempt at the bottom of the ChatViewController.swift file commented out (I thought it might be useful in the future).

What I want to say is that we should discuss if we should ditch the out-of-the-box solution that MessageKit provides. I don't want to say that we should get rid off MessageKit per se, because there aren't any feature rich alternatives (I did a little research in that matter), and building our own solution is probably too much work. But we should maybe just use a plain chatView-example (as I did) and add features manually. 

Maybe it's just me, but I really would like to see anyone else trying to work with the current ChatView (displaying video thumbnails would be a good start #117 ) to get a second opinion about this matter.

**Comment by r10s** [comment]
k, we will decide this later and reopen this issue as needed.

**Comment by Simon-Laux** [comment]
i think its time to reopen this

**Comment by r10s** [comment]
k, but still, that is of very low priority.

first, other things need to be fixed with the message list, as of flickering on sending and the nervous input area.
