### ISSUE TITLE
scan account broken

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#1290]
on new installation:

- after the question "allow delta chat to access camera for qr code scan", a white screen is shown, waiting a bit let the app crash (not sure about the latter)

- on restart, camera works, however, the progress dialog is stuck at "one moment ..."

the bug appears on [current master](https://github.com/deltachat/deltachat-ios/commit/57dd4093297fe7ff258424f867b49e827e91d45c) as well as in https://github.com/deltachat/deltachat-ios/pull/1286, however, the latter seems to be unrelated to https://github.com/deltachat/deltachat-core-rust/issues/2522 as due to restart, the events should arrive.

the bug does not exist in current app store release (1.20.5), so it is introduced recently.

might be advantageous to target this issue after fixing https://github.com/deltachat/deltachat-core-rust/issues/2522 as it may be hard to distinguish these bugs.

**Comment by cyBerta** [comment]
after diving into this bug, I would also like to propose to wait until deltachat/deltachat-core-rust#2522  is fixed. The problem is related to missing events from the core. 

I've added testwise the following code to the WelcomeViewController initialization: https://github.com/deltachat/deltachat-ios/blob/master/deltachat-ios/Controller/WelcomeViewController.swift#L68

```
        if (dcContext.addr != nil  && !dcContext.isConfigured()) {
            addProgressAlertListener(dcAccounts: dcAccounts, progressName: dcNotificationConfigureProgress, onSuccess: handleLoginSuccess)
            showProgressAlert(title: String.localized("login_header"), dcContext: dcContext)
            dcAccounts.stopIo()
            dcContext.configure()
        }
```

it forces the configure process for unfinished account setups, e.g. when switching accounts.  As a result you get a qr-code/burner account, which is why the general logic still seems to work.
