### ISSUE TITLE
Display issues in Slide Over window on iPadOS 15 

### ISSUE THREAD

**Issue by adan89lion** [deltachat/deltachat-ios#1379]
- Device: iPad Pro 12.9" (2021) (A2461)
- iOS version: iPadOS 15.0.2 (Build 19A404)
- Delta Chat version: 1.22.1
- Expected behavior: The Slide Over window should display message field in the correct position.
- Actual behavior: The message compose field is squeezed below the navigation bar.
- Steps to reproduce the problem:
1. Open Delta Chat in iPadOS 15 in Slide Over view
2. Open a conversation
3. Notice the message field is below the navigation bar
- Screenshots:
![IMG_2325](https://user-images.githubusercontent.com/6585644/138379007-262b1f6d-5940-4df4-b09a-c9d6ea7bab45.jpeg)
- Logs:
N/A (not logged by logger)

**Comment by cyBerta** [comment]
Unfortunately this bug is not reproducable on an iOS emulator (iOS 15 iPadPro 12.9) with the current development branch.
Would you mind to retry with our [tesflight beta release](https://testflight.apple.com/join/uEMc1NxS)? It should be the version 1.24.4


![bugreport_slideover1](https://user-images.githubusercontent.com/2614900/142162005-f89e21ca-a8c6-4579-95e3-5aa2af3ebe4b.png)
![bugreport_slideover2](https://user-images.githubusercontent.com/2614900/142162015-c09e78cf-c104-42af-a98e-08a075d1ce84.png)

**Comment by adan89lion** [comment]
After installing the TestFlight version (1.24.4 (66)), the problem still exist.

This is how to trigger the bug:

1. Open a random app, let's say Safari.
2. Drag DeltaChat from Dock and open in Slide Over view, open a chat room. At this state, the UI is still normal.
3. Force kill the app in Slide Over multitasking screen.
4. Open the app again in Slide Over view.

This is a demonstration video I just captured on my iPad Pro: [Google Drive](https://drive.google.com/file/d/1Ks9h8mdjEUhSz1JsP4ZLiGhDupf45xdI/view?usp=drivesdk)

**Comment by r10s** [comment]
that looks quite similar to the other https://github.com/deltachat/deltachat-ios/labels/message-list issues, we'll try to fix that all together.

**Comment by r10s** [comment]
tracked in https://github.com/deltachat/deltachat-ios/issues/1737 now
