### ISSUE TITLE
landscape mode unusable

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#1441]
when switching from portrait to landscape:
- even if portrait is only one line in the input field, in landscape it will grow to max. 4 lines
- after some seconds (see end of video), the input fields switches to "input only mode"

video:

https://user-images.githubusercontent.com/9800740/150339682-342a0eb1-be96-4400-8859-3bb1491f41c9.MOV

i have the feeling, we're doing too much, not to less :D

**Comment by cyBerta** [comment]
@r10s thanks for the hint. could you please add the device and iOS version?

**Comment by r10s** [comment]
sorry, i forgot :) iphone 7, ios 15.2.1

**Comment by cyBerta** [comment]
@r10s do you also have issues on the iphone7 when switching from portrait to landscape without having the keyboard visible? like described here: https://github.com/deltachat/deltachat-ios/pull/1435#issuecomment-1007704873 ?
On a simulator, I cannot reproduce the bug you described here, however this one https://github.com/deltachat/deltachat-ios/pull/1435#issuecomment-1007704873... I tested the  https://github.com/deltachat/deltachat-ios/pull/1435 with an iphoneX (because of the notch) simulator, my phone, and an iPad simulator but it seems that more devices need to be tested here...

**Comment by r10s** [comment]
yip, it also happens without keyboard, but it seems to be a bit random:

in the video, at the beginning, input-only is shown, in the middle, the "correct" view:

https://user-images.githubusercontent.com/9800740/150351810-f0735d5d-b133-4b36-b70c-ce4a92505df6.MOV

the difference in the video is little entered text, however, i could not reproduce that this really makes a difference.

**Comment by r10s** [comment]
it is even worse:
- turn to landscape in chatlist
- open a chat
- you will not be able to see the chat at all, it is all covered by the input field

tested on iphone7 with ios 15.2.1

i consider this as a blocker, this bug was not there in the last release and it is probably also bad on ipads.

maybe we can just remove the "full keyboard view completely" - it has only some benefits only on tiny screens (iphone se1 only) and obviously many issues.
