### ISSUE TITLE
too much scrolling in message view

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#1516]
the message view still does much too much scrolling.

eg. when sending a message, it happens regulary, that the view does not just scroll _up_ but scrolls down to the new message.

there are many more similar situations, on sending etc. i still think, we are doing too much :)

**Comment by cyBerta** [comment]
One thing that really annoys me is if I read a message and the message jumps after a minute, because the time label was updated and the list is already near the bottom. I will take care of that issue in a separate PR now. 

Another improvement would be that the list isn't scrolled down automatically as long as the user drags the list.

**Comment by r10s** [comment]
tracked in https://github.com/deltachat/deltachat-ios/issues/1737 now
