### ISSUE TITLE
webxdc: "onunload" does not work

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#1583]
maybe it is just a bug in the testing tool (https://github.com/webxdc/webxdc-test/pull/1), maybe a switch is missing - however, "onunload" is an important thing needed for sendUpdate()-optimizations, we should make that work somehow.

**Comment by r10s** [comment]
seems to be missing by definition.

https://stackoverflow.com/questions/51940005/wkwebview-localstorage-becomes-null-on-window-close shows a way to trigger onunload:

```
func webViewDidClose(_ webView: WKWebView) {
    // Trigger the unload event before closing the web view
    webView.evaluateJavaScript("dispatchEvent(new Event('unload'));")

    // Give the content some time to respond to the event, and then destroy the web view
    DispatchQueue.main.asyncAfter(deadline: .now() + .milliseconds(500)) {
        self.webView?.removeFromSuperview();
        self.webView = nil
    }
}
```

but that seems to be tricky, timeouts, the author also says localStorage is already null. that seems to need some tests and investigations; at https://github.com/webxdc/webxdc-test/pull/1 we have a test for `onunload` meanwhile.

**Comment by cyBerta** [comment]
according to https://developer.mozilla.org/en-US/docs/Web/API/Window/unload_event#usage_notes developers should not rely on unload events, since they are not well supported, especially in the mobile context. 

Alternertively https://developer.mozilla.org/en-US/docs/Web/API/Document/visibilitychange_event is proposed in the same documentation.

If we can use an approach on all platforms that doesn't require fighting against the intended platform specific behavior (in case of iOS, but maybe also Android), I would suggest to try that route.

**Comment by r10s** [comment]
if `visibilityChanged` works on all platforms, we can go for that, however, i have not tried it on ios nor it is part of the webxdc-test yet.

wrt onunload: the advantage is, that it is very well known since 20+ years and probably many js code just uses it and could be used without adaption - also in mozilla browsers, these events work ;)

**Comment by cyBerta** [comment]
PR to test `visibilityChange` on all platforms: https://github.com/webxdc/webxdc-test/pull/2
