### ISSUE TITLE
ios dark mode support is very poor

### ISSUE THREAD

**Issue by dignifiedquire** [deltachat/deltachat-ios#163]
Some parts are inverted, some are not. Some have very poor contrast, or strange artifacts.

**Comment by r10s** [comment]
okay, official xcode 11 is out and ii had a closer look. due to the recent cleanups, at least the title in most viewcontrollers is fine. same for the settings.

todo: 

- in chatlist-view and contact-view (that is also used for member-view and group-creation-view) the title of the chat resp. contact is rendered in a dark color. there is probably some "foreground" color or so that can be used. the subtitle is fine, probably by coincidence as rendered in 50% gray.

- the chat-view with the MessageKit thingie is currently not respecting dark-mode at all, so, at least things stay visible. wondering if there is an update for that or so, but as we've defined many colors on our own, we need to adapt this probably (also) manually. see the android-dark-mode for some nice-working color for the chat-bubbles etc.

- the title in the chat-view is drawn with. a transparent grey.

- in the qr-show-view and in the group-info-view, there is a row with own-avatar (for the headline) this is also rendered in light-mode. however, wondering if we want to have this row at all here (just in case it is hard to fix)

**Comment by r10s** [comment]
oh, and, not to forget: the input field shows light-white on white text ;)

**Comment by nayooti** [comment]
Here is a temporary solution:

Disabling darkmode support for a single ViewController or disable darkmode support for the whole app (2 lines of code).
https://stackoverflow.com/questions/56546267/ios-13-disable-dark-mode-changes

**Comment by r10s** [comment]
@nayooti thanks for pointing to that, very welcome hint!
