### ISSUE TITLE
start using JSON-RPC on iOS

### ISSUE THREAD

**Issue by adbenitez** [deltachat/deltachat-ios#1847]
Android counterpart: https://github.com/deltachat/deltachat-android/pull/2479

Since Delta Chat Desktop and bots starting using JSON-RPC, we have a divergence in the way our clients use core in the three platforms, so to start mitigating this situation the aim is to start by using JSON-RPC for any new API

<details><summary>Async futures in Swift</summary>

https://developer.apple.com/videos/play/wwdc2021/10132 minute 32, async futures

```swift
class ViewController: UIViewController {
 private var activeContinuation: CheckedContinuation<[Post], Error>?
 func sharedPostsFromPeer() async throws -> [Post] {
  try await withCheckedThrowingContinuation { continuation in
   self.activeContinuation = continuation
   self.peerManager.syncSharedPosts()
 }
}
extension ViewController: PeerSyncDelegate {
 func peerManager (_ manager: PeerManager, received posts: [Post]) {
  self.activeContinuation?.resume (returning: posts)
  self.activeContinuation = nil // guard against multiple calls to resume
 }
 func peerManager (_ manager: PeerManager, hadError error: Error) {
   self.activeContinuation?.resume(throwing: error)
   self.activeContinuation = nil // guard against multiple calls to resume
 }
}
```
</details>

**Comment by Simon-Laux** [comment]
So while I started implementing it I found out that the apis used code example above and "async/await"-syntax in general are only available in iOS 13 or newer. So unless we want to work with callbacks or use third party libraries like https://github.com/vadymmarkov/When, we need to upgrade min iOS version to 13. (which makes sense anyway because then we could use Swift UI which would make iOS dev and maintainance simpler for us - even though I admit that it kinda hurts me that some people on older iOS devices will not be able to use new versions of DC anymore, on that matter it would make sense to look at our install stats: "how many users are actually under iOS 13?")

**Comment by r10s** [comment]
there is `dc_jsonrpc_blocking_call()` now, that should do.

however, regarding size hickups on android, there is no need to be fast adding that fast without need or to track that. once an api that is needed it will be added anyways at that moment - and also get a real-life  test immediately.

**Comment by r10s** [comment]
no need for an explicit issue, we'll use and add [`dc_jsonrpc_blocking_call()`](https://github.com/deltachat/deltachat-core-rust/pull/4389) or whatever is needed when it is needed. probably not far aways, when it comes for adding reactions.

cross-linking #1727 and 1728

**Comment by r10s** [comment]
meanwhile, jsonrpc was needed and added by https://github.com/deltachat/deltachat-ios/pull/2039
