### ISSUE TITLE
no notifications or delayed notifications

### ISSUE THREAD

**Issue by mytickets617** [deltachat/deltachat-ios#1882]
- Device: iphone, ipad various versions
- iOS version: 16.5
- Delta Chat version: 1.36.4
- Server: Dovecot, push enabled
- Expected behavior: receive a notification on new IM
- Actual behavior: no notifications
- Description:
There are multiple DC support and github threads, previously closed, reporting same issue. Not clear why they were closed though as same issue remains unresolved. This renders the app useless as a Chat tool. The suggested AppleMail workaround is not feasable. Here is the latest, which references several prior tickets:
https://support.delta.chat/t/notifications-missed-updates-on-ios-mailbox-org/2559

**Comment by r10s** [comment]
notifications are tricky on ios when not using a central server or at least the help of the mail servers.

current expected behaviour is that we _really_ make use of the time slots the system provides to us - at best, this is every ~20 minutes, when the app is used less often, even less.

can you please provide more information about what is shown in "settings / connectivity view" and in  the log "settings / advanced / view log".

cmp. https://github.com/deltachat/deltachat-core-rust/issues/4420 for ongoing improvements (we have this issue on the radar all the time btw, but we usually track only really actionable items)

**Comment by r10s** [comment]
> Notifications: Connected

that should show more information, sth. as:

<img width=320 src=https://github.com/deltachat/deltachat-ios/assets/9800740/84ee82d6-02f9-4c1a-930d-cf73537f2701>



> Which Log keys do you need to see?

to get a grip on your issue, all parts of the log may be of interest (in fact, it is not a log but mainly a list of variables), you can of course  remove personal information as name or email. esp. the part above arch=64 is interesting:

<img width=320 src=https://github.com/deltachat/deltachat-ios/assets/9800740/9f68cfbf-7b6c-451d-9f28-84e48e27c995>

**Comment by mytickets617** [comment]
Debug value was reported above.
The iphone device was sitting without anyone touching for the past ~2hr. It received 1 notification just now surprisingly. Also, now "Notifications:" lists "Delayed, Checked at 06:17 PM, 05:52 PM, 05:26 PM, On average every 25 minutes.

**Comment by r10s** [comment]
yip, the "sattelite" and other icon stuff is important as well as everything above (that shows times)

**Comment by JoeMcNuggets** [comment]
I've lost a log file, but I'm sure I've seen the next case:
- all the checks successfully passed in the time message arrived
- no notification received

I have to idease:
- iOS allows app to fetch messages, but it can't send notification for some reason
- iOS allows app to wake up, but it can't pull messages for some reason

**Comment by r10s** [comment]
concrete actionable items to target this issue are in #2009, #2010 and #1830 now.

we aim to do a testflight with these changes soon. if there are remaining issues with _polling_ every ~20 minutes, we'll open on-point 

main remaining issue of the initial report is the "feature proposal" of doing notifications with the help of servers (you cannot have instant notifications without on iOS, IMAP push does not work on iOS, btw). we aim to move forward on that also soon :)

**Comment by r10s** [comment]
> notify-remote-launch=0x

we just released 1.42.7 on testflight, can you please check, if that `notify-token`  etc. show something meaningful meanwhile? and what "connectivity" shows?

note: 1.42.7 does not push from server to device (that requires adapted servers), but should poll at about every 20 minutes in case the app is in use. otherwise, apple still throttles, there is not much we can do about it -  but of course, we should fix all  bugs avoids making use of the few slots,  [as we aimed for in the past](https://github.com/deltachat/deltachat-ios/issues?q=is%3Aissue+is%3Aclosed+label%3Anotify+), as good as we can :)

**Comment by r10s** [comment]
thanks for clarifying, there is now https://testflight.apple.com/join/uEMc1NxS with deltachat-ios 1.42.8 using core 1.132.1 that should improve notification :)

**Comment by r10s** [comment]
[1.44 meanwhile has "real" PUSH notifications for supporting providers](https://delta.chat/en/2024-03-12-jumbo44) and also fixes quite some crashes that slow down notifications otherwise.

closing this issue as i do not see an actionable item left.

if needed, please file a new issue for 1.44 with fresh information.
