### ISSUE TITLE
chat view: display issue with long names

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-ios#1899]
See screenshot, avatar is not shown fully:
<img width="375" alt="1686265544 826076" src="https://github.com/deltachat/deltachat-ios/assets/18725968/d7f226ed-891c-48cd-bdbb-95303f45ebf3">

**Comment by r10s** [comment]
ftr, the issue is triggered by subtitle (email address in this case), having long group or contact names alone is fine

**Comment by r10s** [comment]
there was an attempt to fix it that introduces more issues than it opened: https://github.com/deltachat/deltachat-ios/pull/1944

so, these constraints needs some closer look. i also think, they are too complicated, eg. `ChatTitleView::containerView` is maybe superfluous

**Comment by r10s** [comment]
the issue with the larger icon ...

<img width=200 src=https://github.com/deltachat/deltachat-ios/assets/9800740/f7acc67a-d94f-43e2-9225-426e7bf59dd1>

... was unrelated to the first fixing attempt but was in the layout since forever; it just became more visible by having a subtitle that is longer than the title.
