### ISSUE TITLE
URLs that end on "." aren't detected correctly

### ISSUE THREAD

**Issue by cryptosteve2** [deltachat/deltachat-ios#2293]
- iOS version: iOS 17.6.1 // iPadOS 17.6.1
- Device: iPhone 13 Pro // iPad Pro 3rd generation
- Delta Chat version: v1.46.9
- Expected behavior: detect the complete url as url
- Actual behavior: only a part is detected as url on iOS // iPadOS (but the complete one on MacOS)
- Steps to reproduce the problem: try url or see screenshots. URL: https://www.sportschau.de/fussball/championsleague/bayern-und-dortmund-spielen-gegen-barca,champions-league-auslosung-136.html#:~:text=Jeder%20der%2036%20Klubs%20-%20bislang%20waren%20es%2032%20-%20spielt%20viermal%20im%20eigenen%20Stadion%20und%20viermal%20ausw%C3%A4rts.%20Schwere%20Ausw%C3%A4rtsaufgaben%20erwischten%20unter%20anderem%20die%20Bayern%2C%20die%20in%20Barcelona%20auf%20ihren%20Ex-Trainer%20Flick%20treffen%2C%20sowie%20Leipzig%20und%20Dortmund%2C%20die%20nach%20Madrid%20reisen%20m%C3%BCssen. 
- Screenshots:
iOS // iPadOS:
![IMG_0075](https://github.com/user-attachments/assets/26e941b1-0379-4f9b-94e9-9ba387327b62)
MacOS:
![20240829@220637](https://github.com/user-attachments/assets/fc9bf270-d088-47de-93c9-2b9e5ec89169)

- Logs:

**Comment by zeitschlag** [comment]
Thank you for that bug report, I can reproduce it and had a quick look at it, but haven't come up with a solution yet.

---------

## Note to self

- [`MessageLabel.parse`](https://github.com/deltachat/deltachat-ios/blob/05995012805d9ffc4493121dfd87f6c2b07748b5/deltachat-ios/Chat/Views/MessageLabel.swift#L338) fails for this URL:

```swift
// Get all Checking Types of detectors, except for .custom because they contain their own regex
let detectorCheckingTypes = enabledDetectors
    .filter { !$0.isCustom }
    .reduce(0) { $0 | $1.textCheckingType.rawValue }
if detectorCheckingTypes > 0, let detector = try? NSDataDetector(types: detectorCheckingTypes) {
    // doesn't match https://www.sportschau.de/fussball/championsleague/bayern-und-dortmund-spielen-gegen-barca,champions-league-auslosung-136.html#:~:text=Jeder%20der%2036%20Klubs%20-%20bislang%20waren%20es%2032%20-%20spielt%20viermal%20im%20eigenen%20Stadion%20und%20viermal%20ausw%C3%A4rts.%20Schwere%20Ausw%C3%A4rtsaufgaben%20erwischten%20unter%20anderem%20die%20Bayern%2C%20die%20in%20Barcelona%20auf%20ihren%20Ex-Trainer%20Flick%20treffen%2C%20sowie%20Leipzig%20und%20Dortmund%2C%20die%20nach%20Madrid%20reisen%20m%C3%BCssen.
    // for whatever reason.
    let detectorMatches = detector.matches(in: text.string, options: [], range: range)
    if detectorMatches.isEmpty == false {
        debugPrint(detectorMatches)
    }
    matches.append(contentsOf: detectorMatches)
}
```

**Comment by cryptosteve2** [comment]
Btw, maybe it's not deltaChat related? I have the same issue im MacOS Apple Mail  ... 
![20240903@134719](https://github.com/user-attachments/assets/51c88415-60b6-4d42-8cab-c5e46b66e348)

**Comment by r10s** [comment]
we discussed internally about that issue, and came to the conclusion, that we cannot do reasonably much upon that. in theory, we could try to detect urls on our own, but we would probably open much more issues with that that closing this one.  parsing text and detecting URLs is a hard job when it comes to cornercases. it is good to leave that up to apple. 

for the concrete issue: the bug is that depending on the final dot, the URL is marked as such only "half".

for the final dot: if that belongs to the URL or not is not really detectable. if you have the text 
`i like http://foo.bar/#hilight=baz.`  
the URL may or may not include the final dot. looking at URLs existing in the wild, however, it is reasonable to assume that URLs end less often with a dot than sentences - this is probably what apple assumes here - as well as github, btw, when looking at the initial post. but as said, we would leave that up to apple.
