### ISSUE TITLE
When searching it shows the amount of messages the search term is in, not the occurrences of the search term

### ISSUE THREAD

**Issue by Amzd** [deltachat/deltachat-ios#2313]
- iOS version: iOS 17
- Device: iPhone X
- Delta Chat version: master
- Expected behavior: If I search for "example" and I have received a message with the word "example" in it multiple times, I'd expect to be able to iterate over each occurrence with the arrows instead of only over each message.
- Actual behavior: It shows results per message in which the word occurs but not per occurrence of the search term.
- Steps to reproduce the problem: 
  - Send message "example example", 
  - search for "example", 
  - expected: 2 results, 
  - actual: 1 result.
- Screenshots:
- Logs:

**Comment by Amzd** [comment]
I can pick this issue up myself if this is not expected behavior

**Comment by r10s** [comment]
assuming, this is about the in-chat-search:

well, it is the expected behaviour. the result counts _messages_, not _text occurrences_.

as the message list is virtual, so at no point all text is loaded, i also do not see an easy and performant way to change this in UI, without the help of [deltachat-core-rust](https://github.com/deltachat/deltachat-core-rust/). the search itself is done by deltachat-core-rust using some somehow performant SQL query; this query does not count or know the number of text occurances. of course, that can be changed, but then the question is, if that is worth the effort.

but maybe i also have overseen an aspect that would make counting _text occurances_ easy.

but even if, we should consider carefully: whatsapp as well as signal counts matches the exact same way (telegram also counts _messages_, but shows the result differently)

that said, thank you very much for considering to contribute to deltachat-ios, @Amzd - maybe there are other, more UI related things that one could pick up :)
