### ISSUE TITLE
Back swipe doesn't work in xdc apps

### ISSUE THREAD

**Issue by Amzd** [deltachat/deltachat-ios#2317]
- iOS version: iOS 16
- Device: iPhone X
- Delta Chat version:
- Expected behavior: swipe from left edge should close pushed vc 
- Actual behavior: doesn't do anything, probably because it's a web view and the back swipe is reserved to go back in history?
- Steps to reproduce the problem: open any xdc app and try to close it with a swipe
- Screenshots:
- Logs:

**Comment by r10s** [comment]
this is on purpose as apps, esp games, using comparable gestures are otherwise terminated unexpectedly - which is much worse, when a new highscore is ruined by that :)

**Comment by Amzd** [comment]
I see. That would be annoying. Still think it's also annoying that you can't swipe back when you go into eg a todo list

**Comment by r10s** [comment]
maybe. issue with an option will then be that there is no consistent way to exit apps :/  that will look even more as bug - or needs explanation/care of users. also, we try to avoid options wherever possible.

maybe we should also consider to re-add the swipe option in general. this might be the better tradeoff:

- since it was removed, screens got bigger (esp. we devs has an iPhone SE1 that time)
- the decision that time was easy, as there were no tools at all. @adbenitez can you say what is the worse/fastest game to try that may interfere with swipe to go back? (@adbenitez did quite some of the existing games)
- in general iOS is pretty good at detecting these swipes, one has really to start outside the screen - and there are anyway swipes from top/bottom we cannot disable

**Comment by Amzd** [comment]
Idk how fast the games are but we can also store the pushed webxdc vc for a couple seconds so if you click the same webxdc item, it will give the stored vc instead of restarting the web view? So if you accidentally exit it wouldn't discard anything.

**Comment by Simon-Laux** [comment]
I guess if the webxdc app should configure it, then it should be a property in the [`webxdc manifest.toml`](https://webxdc.org/docs/spec/format.html#the-manifesttoml-file)

**Comment by Amzd** [comment]
#2322 made a concept that fixes some of your concerns with backswipe interfering with games.

https://github.com/user-attachments/assets/6cbf6e2c-12ce-4891-85aa-916df02b3156

**Comment by r10s** [comment]
put to resurrection, see corresponding PR for reasoning
