### ISSUE TITLE
minor side effects of "ScrollView jumping improvements"

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#2323]
["ScrollView jumping improvements" PR](https://github.com/deltachat/deltachat-ios/pull/2315) introduced some side effects that need to be targeted:

- the icon shown on swipe-to-reply is flipped
- ~~tapping the system clock does not scroll _up_ as usual, but scrolls _down_~~ EDIT: might be okay, may be considered even as a fix as we no scroll to the most recent information; the scroll-up in eg. whatsapp is also more random as it scrolls just somewhere to the middle (as more messages are loaded there immediated)
- the scrollbar is gone
- input field is missing after using camera if the _keyboard was not expanded_ before

cc @Amzd

**Comment by Amzd** [comment]
Did not fix the new behavior of status bar scrolling to the most recent message yet as other messengers (like discord) also do this. If users really want this we can always look at this again later. We will need to add a scrollview at the same level as the tableview which can intercept the status bar tap. So we'll need to use a UIViewController instead of UITableViewController.

Other issues are fixed in PR
