### ISSUE TITLE
child coordinator list is never cleared?!

### ISSUE THREAD

**Issue by cyBerta** [deltachat/deltachat-ios#295]
At the moment, pushing ViewControllers to the view controller stack leads to the addition of the corresponding coordinator in a child coordinators list (comp. https://github.com/deltachat/deltachat-ios/blob/master/deltachat-ios/Coordinator/AppCoordinator.swift#L48 or https://github.com/deltachat/deltachat-ios/blob/master/deltachat-ios/Coordinator/AppCoordinator.swift#L157). This list seems to be never cleared though if view a ViewController is popped from the stack which smells like a bug and memory issue.

@nayooti @jonasreinsch can you tell us if there's some hidden magic that does the cleaning of the list if a ViewController is popped from the stack?

Could you please also give some information about the general purpose of keeping the coordinators in that list?

**Comment by nayooti** [comment]
The viewcontrollers only hold a weak reference on the coordinators (otherwise there would cause a retain cycle between viewcontroller > coordinator -> navigationcontroller -> viewcontroller). Therefor we need this list to keep a strong reference to the coordinators, otherwise they would be deallocated once the method in which they are instantiated returns.

It is definitively a leak that the list is not cleared. I think I found already a solution for this based on this post.
[https://benoitpasquier.com/coordinator-pattern-navigation-back-button-swift/](url)

It only requires only a few adjustments and leaves the viewcontrollers untouched.

I will take care of this in the next couple days.

**Comment by r10s** [comment]
the link is weird, this is the correct one: https://benoitpasquier.com/coordinator-pattern-navigation-back-button-swift/

**Comment by nayooti** [comment]
Yeah, that's the link.
Not sure what went wrong with the link in my post.

**Comment by r10s** [comment]
wrt clearing childCoordinators: https://www.hackingwithswift.com/articles/175/advanced-coordinator-pattern-tutorial-ios

the strong reference is in fact needed, this is an issue that happens when it is not done: https://github.com/deltachat/deltachat-ios/issues/323 - although set, it is gone when the viewcontroller wants to access it. a bit weird designed by apple imho.

**Comment by cyBerta** [comment]
@nayooti any updates on this issue?
