### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by lutzroeder** [deltachat/deltachat-ios#41]

**Comment by jonasreinsch** [comment]
@r10s not sure what is the plan here (we talked about it I think a long time ago), probably we also should check all included libraries here https://github.com/deltachat/deltachat-ios/blob/master/Podfile ?

**Comment by dignifiedquire** [comment]
I checked all the ones I added, and they should all be MIT or MIT compatible.

**Comment by hpk42** [comment]
On Tue, Jan 22, 2019 at 04:46 -0800, Friedel Ziegelmayer wrote:
> I checked all the ones I added, and they should all be MIT or MIT compatible. 

sounds good. The overall license for the repo would then be GPL because
Jonas's and "humanlikedesasters" Contributions are licensed with merlinux and 
there is a *potential* plan to ask for some money for appstore-installs at some 
later point in the future ... but that could also happen if we license with MPL or so.
In any case, GPL for now allows people to inspect/build/modify/push/use things with 
their own device but indeed not through the apple app store.

**Comment by dignifiedquire** [comment]
Also note, that all contributors should ack in written form in an issue that they are okay with the license being used (and on every other license change).

**Comment by hpk42** [comment]
On Tue, Jan 22, 2019 at 05:11 -0800, Friedel Ziegelmayer wrote:
> As I mentioned before, the GPL is unfortunately in direct opposition to the AppStore: https://apple.stackexchange.com/questions/6109/is-it-possible-to-have-gpl-software-in-the-mac-app-store 

yes, but the fact that the github repo would be GPL licensed does not prevent
us from pushing it to the app store with a different license, does it? 
see also: https://github.com/signalapp/Signal-iOS

**Comment by dignifiedquire** [comment]
A quick google search leaves me to believe that it is complicated and I am unclear on what the actual legal situation is:

- https://github.com/signalapp/Signal-iOS/issues/155
- https://github.com/signalapp/Signal-iOS/issues/155

**Comment by jonasreinsch** [comment]
> On Tue, Jan 22, 2019 at 04:46 -0800, Friedel Ziegelmayer wrote: I checked all the ones I added, and they should all be MIT or MIT compatible.
> sounds good. The overall license for the repo would then be GPL because Jonas's and "humanlikedesasters" Contributions are licensed with merlinux and there is a *potential* plan to ask for some money for appstore-installs at some later point in the future ... but that could also happen if we license with MPL or so. In any case, GPL for now allows people to inspect/build/modify/push/use things with their own device but indeed not through the apple app store.

**Comment by jonasreinsch** [comment]
@hpk42 I think what Friedel said (that all contributors have to agree in written form to the licence and possible licence changes) is correct and independent of any agreement assigning usage rights that might/will be signed between e.g. me and Merlinux (because the copyright, at least according to German law, is always attached to the actual natural person, not with orgs (only usage rights can be assigned)). This also simplifies things because you can treat all contributors the same and let them sign the same kind of document.

ATM, this should be relatively simple still because there are only 6 contributors I think (does anyone know why humanlikedisaster is missing from the overview here: https://github.com/deltachat/deltachat-ios/graphs/contributors?from=2017-11-05&to=2019-01-22&type=c )

**Comment by hpk42** [comment]
On Tue, Jan 22, 2019 at 05:57 -0800, Jonas Reinsch wrote:
> @hpk42 I think what Friedel said (that all contributors have to agree in written form to the licence and possible licence changes) is correct and independent of any agreement assigning usage rights that might/will be signed between e.g. me and Merlinux (because the copyright, at least according to German law, is always attached to the actual natural person, not with orgs (only usage rights can be assigned)). This also simplifies things because you can treat all contributors the same and let them sign the same kind of document.

not sure that's entirely correct ... copyright and licensing rights are not the same thing. 
you cannot assign copyright to others under german law for example but you can assign
licensing rights to someone else, exclusively or non-exclusively. 

So it's not the copyright holders but those with sufficient licensing
rights who need to agree on a license (there can be multiple parties who
exercise licensing rights on the same work, one agreement is enough).
I'll meet Janka later and will verify if my understanding is correct but
we had a similar discussion when we re-licensed the core to MPL. 

> ATM, this should be relatively simple still because there are only 6 contributors I think (does anyone know why humanlikedisaster is missing from the overview here: https://github.com/deltachat/deltachat-ios/graphs/contributors?from=2017-11-05&to=2019-01-22&type=c )

it's probably also workable to ask for agreement again with those 6 if needed.

**Comment by jonasreinsch** [comment]
ah, understood, makes sense. So the contributors would give licencing rights to Merlinux and Merlinux would then decide which licence to use (and decide on future licence changes).

**Comment by hpk42** [comment]
On Tue, Jan 22, 2019 at 09:00 -0800, Jonas Reinsch wrote:
> ah, understood, makes sense. So the contributors would give licencing rights to Merlinux and Merlinux would then decide which licence to use (and decide on future licence changes).

it's a little more involved but roughly that: 

- merlinux gives licensing rights for certain contributions,
  concretely for those from jonas, humanlikedesaster, alla and 
  also nayooti? -- i think it was a compagnon of Jonas but 
  might be mistaken.

- Others, particularly friedel's contributions are licensed by him, 
  not merlinux, and they are licensed as MIT.

- The overall work is usable under the GPL (or whatever license we
  eventuallhy settle i am not so sure yet)

Janka is sitting next to me and seems to agree ;) 

holger

**Comment by comradekingu** [comment]
The MPL is a failed license, and to my knowledge prevents inclusion of anything that is GPLv3 (like the Android client), as opposed to the opposite. MPL gives less protections, and more needless restrictions than the GPLv3+ or AGPLv3+, from the perspective of ensured user freedoms. The license file still missing, and that is a good opportunity to at-least dual-license it, like http://www.videolan.org/vlc/download-ios.html
E-mail will be around for a while, and coat-tailing to Apple's terrible practices in that time-frame creates more problems than it solves.
One of which is the ability to effectively being able to re-license (like the above) when it is convenient.

**Comment by strypey** [comment]
IANAL but I'm pretty sure that in most jurisdictions, software is automatically proprietary (covered by ARR copyright). So unless and until there is a license that says otherwise, the iThing version of Delta Chat is proprietary. I doubt this is the outcome you want, so I respectfully suggest you reopen this issue until you can agree on a free code license that suits your needs and works with the iThing store.

FWIW I'd really like to see an anti-trust action against Apple for their anti-copyleft policy. It creates headaches for a lot of devs of cross-platform apps, who prefer to use a copyleft license.
