### ISSUE TITLE
Ipad: app crashes on UIAlertController (action sheet) presentations

### ISSUE THREAD

**Issue by nayooti** [deltachat/deltachat-ios#480]
On Ipad UIAlertController with style **action sheet** is not supported. Therefor app crashes.

For instance:
NewChat -> Choose Contact -> here an actionSheet is supposed to show up 

There might bei other cases. 

- Device: happes on all IPADs 
- iOS version: 13
- Delta Chat version: 1.0.1
- Expected behavior:
- Actual behavior:
- Steps to reproduce the problem:
- Screenshots:
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-01-09 at 13 15 32](https://user-images.githubusercontent.com/5249565/72066969-2dc36800-32e2-11ea-86b0-66006fc9b4f1.png)

- Logs:

Logs may contain private data 
which shall be removed or anonymised prior to posting.
-->

**Comment by r10s** [comment]
i would have expected apple to show just a normal alert in this case. but well ...

**Comment by r10s** [comment]
i think, we should do a hot fix now and upload a 1.0.2 to the app store today.

**Comment by nayooti** [comment]
I will take care of this later. 
Not sure if this is the only UIAlert-ActionSheet, right now.

**Comment by r10s** [comment]
@nayooti i am also looked into it. it affects several/most/all .actionSheets. i think we should just use  .alert instead of .actionSheets on ipads unconditionally, so that we are always safe.

in general, .actionSheets seem to be possible under some circumstances also on ipad, see eg, https://stackoverflow.com/questions/15098660/actionsheet-on-ipad , however, i would not try to make this decision on every single existing .actionSheet just now.
