### ISSUE TITLE
add support for iphone 5c and older ios versions

### ISSUE THREAD

**Issue by Thyphex** [deltachat/deltachat-ios#498]
Is it possible to add support for lower ios versions? I have an iPhone 5c ios 10.3 and I cant download delta chat because of it.
All chat apps work on my phone.
They mostly support ios 9 and up.

**Comment by r10s** [comment]
@Thyphex are you up on helping on this issue?

i think, in theory, we can support versions down to the [iphone4s which got ios 9.3.6](https://en.wikipedia.org/wiki/IPhone_4S) at some point and which is still a possible target in recent xcode versions.

iirc, someone tried that a year ago or so, but it failed because of some libs that do are not supported, not sure, if this still an issue, lots of changes since then.

**Comment by r10s** [comment]
here is an older discussion about it: https://github.com/deltachat/deltachat-ios/issues/18 - so, according to the stats there, with ios11 as the current minimum we target **97%** of all devices - this is similar to the [**96%** on android](https://github.com/deltachat/deltachat-android/pull/1115).

seeing these stats, i do not think it is worth the effort. after all experiences, trying to target old system results in disproportionately many issues which may result in high maintenance costs.

**Comment by r10s** [comment]
just checked to compile with 9.3 that works with iphone5c - compiling succeeds, however, i cannot test it as this is not supported by the current xcode version simulators. the oldest thing that can be simulated there is iphone5s - and this is already supported and works. so, i fear with iphone5c and older, you're out of luck :/

**Comment by r10s** [comment]
i also encountered that, while 9.3 compiles it runs much slower on iphone 5s in simulator - target 11.1 works perfectly on 5s. so, there is already a first issue we had to fix ;) as said, it is too expensive and not worth the effort imho.
