### ISSUE TITLE
input field hides and appears again very slowly

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#521]
steps to reproduce:

- open a chat containing some images
- open an image
- close the image by _swiping down_
- => the input field is hidden _but_ reappears slowly in a minute or so

thanks @paulaluap for figuring that out :)

**Comment by r10s** [comment]
maybe this is related to this ui glitch: https://github.com/deltachat/deltachat-ios/issues/427

**Comment by nayooti** [comment]
Only solution (workaround) I came across so far:
If we present the QuickLockController from inside a UINavigationController the InputBar behaves normal.
We still can use swipe gestures to swipe through the gallery items. And iOS13-devices can swipe-to-dismiss (older devices need to use the close button).
Another drawback is that we are **loosing QuickLookController's nice swipe+shrink-animation**. 

That is the current state: 
I will setup a PR with this solution so you can have a try. 

I am not even sure, if this bug is fixable if I am completely honest:
What I figured out is, if you set 
` messagesCollectionView.keyboardDismissMode = .onDrag` in `MessagesViewController` in `line 152`, you get this very nice feature that you can dismiss the keyboard by swiping down the screen. Now when you select a media item, swipe down to dismiss the preview (trigger the bug), you will find that the keyboard will appear also slowly (same what happens to the input field). It really made me believe that is probably a iOS-bug.

**Comment by r10s** [comment]
can't we get rid of the fading in & out of the message fields _completely_? so that it is just shown always and unconditionally?

**Comment by nayooti** [comment]
It's maybe possible, but it's definitely not easy due to the very complex nature of MessageKit.

**Comment by r10s** [comment]
we forked MessageKit, so at least, we can do changes as needed. maybe it is worth a look.

**Comment by nayooti** [comment]
ok, I will make another attempt.

**Comment by r10s** [comment]
this is currently fixed by #560 , however with some side-effects, #570 

also, #560 hides the but more coincidentally, so, might be it pops up again.

so, it may be worth having a closer looks, also as the quick disappearing and  reappearing is annoying. if we can fix this correctly, we can probably revert #560

**Comment by r10s** [comment]
k, as with https://github.com/deltachat/deltachat-ios/pull/587 the gallery is fullscreen again, we can close this issue. 

the appearing/disappearing ui-glitch from #427 is filed as a separate issue but is not urgent in any way.
