### ISSUE TITLE
Refactor: ContactDetail, SingleChatDetail, GroupChatDetail

### ISSUE THREAD

**Issue by nayooti** [deltachat/deltachat-ios#525]
Currently we have ChatDetailViewController and GroupChatDetailViewController. 
ChatDetailViewController is responsible for displaying ContactDetail and ChatDetail for single chats.

We have now the situation, that these have some cells in common, but also some distinctions. Currently they have a lot of duplicated code, so we should fix this. 

So the idea ist to make a ProfileBaseClass with all common elements, so ContactProfile, SingleChatProfile, GroupChatProfile can inherit from that.

**Comment by r10s** [comment]
> Currently they have a lot of duplicated code, so we should fix this.
> So the idea ist to make a ProfileBaseClass with all common elements, so ContactProfile, SingleChatProfile, GroupChatProfile can inherit from that.

i just had a look, ChatDetailViewController and GroupChatDetailViewController have both about 200 lines each, compared to other swift classes, this appears okay to me. the list-item-views are already shared.

in general, i am no friend of too much abstraction, it tends to be harder to understand. also, we've just refactored/improved this area and it seems to work fine. so, i'd say we fix the remaining bugs and leave this as is for now :)

not part of this issue, however, worth mentioning: due to the core written in rust, there is already a strong model that makes sure, we do not mix up ui and data too much.

btw: good read we discussed internally some weeks ago: https://overreacted.io/goodbye-clean-code/
