### ISSUE TITLE
Delta Chat iPhone App stürzt bei Anmeldeversuch ab

### ISSUE THREAD

**Issue by klaus002** [deltachat/deltachat-ios#755]
- Device: iPhone8
- iOS version: 13.4.1
- Delta Chat version: nicht ersichtlich, gerade geladen
- Expected behavior: Anmeldung bei meinem e-Mail-Server
- Actual behavior: Absturz, kommentarlos
- Steps to reproduce the problem: Mailadr. eingegeben, Passw eingegeben - anmelden ... 60 % "Fehler" (leider nicht weiteresnotiert). Erweitert angewählt, IMAP-Loginname und -Servername eingegeben: jetzt gab es keine Anmelde-Möglichkeit mehr, also zurück, E-Mail und PW nochmal eingegeben, auf "Erweitert" gedrückt, Login-Name-Eingabe angetippt: Absturz.
- Screenshots: keine
- Logs: Schütteln bringt garnichts

**Comment by cyBerta** [comment]
@klaus002 Thanks for your bug report! In order to find your delta chat version, please tap on Settings -> Advanced -> View Log (at the top). If you want to attach logs please tap on Settings -> Advanced -> View Log -> Console and additionally on Settings -> Advanced -> View Log -> Crash reports

Shaking the device doesn't open the debug menu anymore. Thanks for that hint as well, we will need to update the documentation. 

Hallo @klaus002 , vielen dank für deinen Bugreport. Du kannst deine Delta Chat Version herausfinden, indem du auf Einstellungen -> Erweitert -> Protokoll anzeigen klickst. Das würde uns bei der Fehlersuche helfen (aus dem Fehlerbericht wird nicht deutlich, ob du die aktuelle Version vom App Store oder von TestFlight geladen hast). 

Das Schütteln öffnet nicht mehr das Debugmenü, danke für diesen Hinweis, da müssen wir die Dokumentation aktualisieren.

Falls du den Fehler erneut reproduzieren kannst und die Logs anhängen, wäre uns auch bei der Fehlerbehebung geholfen. Gehe dafür auf Einstellungen -> Erweitert -> Protokoll -> Console und auf  Einstellungen -> Erweitert -> Protokoll -> Crash reports.

**Comment by klaus002** [comment]
Hallo cyBerta,
so weit bin ich nicht gekommen, dass ich Einstellungen etc. wählen konnte: der Startbildschirm und der Konfigurationsbildschirm bieten diese Möglichkeit nicht. Auch war die Version nirgends sichtbar.

Ich versuche jetzt zu rekonstruieren, wie ich vorgegangen war (tue es realiter):
Ich lade die App aktuell neu aus dem App-Store, tippe auf "BEI IHREM SERVER ANMELDEN", gebe Mailadresse ein, Passwort und jetzt "login" (rechts oben).
Es erscheint (nach "60 %") "Login als ... nicht möglich...", drücke "OK" (keine andere Wahl möglich). Drücke "Erweitert", trage IMAP-Sicherhei ein (SSL/TLS), -Anmeldename ein, trage -Server ein, trage -Port ein (993) – und drücke dann "<" (links oben), da das "Login" rechts oben grau und inaktiv war. ==> lande bei Willkommen.
Tippe wieder auf "ANMELDEN..." E-Mail-Adresse und Passw sind weg :-(, tippe sie neu. Öffne "Erweitert". IMAP-Sicherheit ist noch eingetragen, alles andere leer :-(. Tippe Anmeldename, Server, dann "Login".
Uff diesmal scheint es zu klappen.
Leider habe ich mir die Schritte beim ersten Mal nicht genau genug gemerkt, schade. Und natürlich gibt es nun kein Protokoll, keine Crash-Reports.

Vielen Dank jedenfalls für Deine Mühe!
