### ISSUE TITLE
add oauth2 support

### ISSUE THREAD

**Issue by nayooti** [deltachat/deltachat-ios#92]

**Comment by nayooti** [comment]
changed title - since regular login seem ok now with latest PR.

**Comment by dignifiedquire** [comment]
Tracking core issue here: https://github.com/deltachat/deltachat-core-rust/issues/119

**Comment by r10s** [comment]
before this issue can be targeted, https://github.com/deltachat/deltachat-core-rust/issues/119 should be fixed - otherwise it is hard to say if things work or not.

**Comment by dumblob** [comment]
> code-wise, there are no things missing.
> 
> but, in contrast to other features, unfortunately, it is _much_ more effort than just a day of coding.
> 
> there is the google compliance thingie that keeps ppl busy, for android we had to create several videos to explain what we're doing and why we need oauth2 and so on.

Thanks for explanation. I came across this when people around started installing iOS Delta Chat, but were unable to get through the "3 point list of possible solutions for Gmail accounts" (partly because it's still quite technically written, but mostly because Google hides all this information in its UIs and the "UI wizards" feel like going in circles).

Oauth2 from my experience shall be the "best way to go" and that's why I came across this issue here :wink:.

> for ios, this was just not started yet - as it is clear already now that it will bind resources for a longer time ...

May I help somehow? I'd be willing to make my hands dirty maybe with some part of the agenda for a month or two if that's what is mostly missing. Any list of things you did in case of Android or things to be done in case of iOS?

**Comment by hpk42** [comment]
@dumblob thanks for the offer to help! 
Do you have some experience with iOS/Swift development?
OAUTH/gmail is not high priority with current devs and also
requires some buereaucracy with google to be allowed
to use it (creating explanation videos, new client ids, etc.).

**Comment by dumblob** [comment]
>Do you have some experience with iOS/Swift development?

Just as a project manager of devs developing them.

**Comment by r10s** [comment]
@dumblob great that you want to help on that!

i just had a closer look: we need some api to set ui-specific [`client_id`](https://github.com/deltachat/deltachat-core-rust/blob/master/src/oauth2.rs#L11), maybe just a [dc_set_config()](https://c.delta.chat/classdc__context__t.html#aff3b894f6cfca46cab5248fdffdf083d) or so. at least for google, this is required iirc, not sure about yandex - maybe you can try to figure that out in detail? that would already be very helpful.

**Comment by dumblob** [comment]
> i just had a closer look: we need some api to set ui-specific [`client_id`](https://github.com/deltachat/deltachat-core-rust/blob/master/src/oauth2.rs#L11), maybe just a [dc_set_config()](https://c.delta.chat/classdc__context__t.html#aff3b894f6cfca46cab5248fdffdf083d) or so. at least for google, this is required iirc

Will try to verify that in the upcoming weeks (it should be described in https://developers.google.com/identity/protocols/oauth2/policies ).

>not sure about yandex - maybe you can try to figure that out in detail? that would already be very helpful.

Will try to take a look at it.

Last week I also devoted some time to the "bureaucracy" behind all this and read everything on https://support.google.com/cloud/answer/9110914 (including all links and links in these links recursively if applicable) and I think I got the bigger picture. Some additional questions:

1. From "Secure Data Handling" in [Additional Requirements for Specific API Scopes](https://developers.google.com/terms/api-services-user-data-policy#additional_requirements_for_specific_api_scopes ):

    > These applications must pass an annual security assessment and obtain a Letter of Assessment from a Google-designated third party.

    1a. How does the annual report look like for the Android app?

    1b. Which "third party" prepared the Letter of Assessment for the Android app?

2. Where on youtube is the video you've used for Android app application process (I found just https://www.youtube.com/watch?v=yPEjYpE_kvc but it doesn't show anything related to Gmail).

3. How to actually run oauth on iOS to make the video? Is there any nightly build with this capability turned on (to show e.g. the consent screen)? I could only find https://testflight.apple.com/join/uEMc1NxS but it doesn't seem to have it turned on nor allow one to simulate (open) the corresponding "consent" forms/panels/views/screens/whatever_its_called etc.

4. By "code-wise there is nothing missing" I suppose you meant it's 100% compliant with everything on https://developers.google.com/identity/protocols/oauth2/policies - or should I (or someone else who understands the codebase better) take a look before making the video and submitting the request for verification process?

**Comment by hpk42** [comment]
On Mon, Jun 15, 2020 at 02:36 -0700, dumblob wrote:
> 1. From "Secure Data Handling" in [Additional Requirements for Specific API Scopes](https://developers.google.com/terms/api-services-user-data-policy#additional_requirements_for_specific_api_scopes ):
> 
>     > These applications must pass an annual security assessment and obtain a Letter of Assessment from a Google-designated third party.
> 
>     1a. How does the annual report look like for the Android app?
> 
>     1b. Which "third party" prepared the Letter of Assessment for the Android app?

IIRC we don't need such reviews at all because we are not running/needing 
any servers besides gmail's own, for Delta Chat OAUTH/GMail users. 
They accepted that (there was some two and fro). 

> 2. Where on youtube is the video you've used for Android app application process (I found just https://www.youtube.com/watch?v=yPEjYpE_kvc but it doesn't show anything related to Gmail).

here is the last video (we made three, the first two were rejected). 

https://www.youtube.com/watch?v=mbZWdu4BOCo

btw, if you mail the delta android playstore address i'll forward you 
the thread of conversations with the Google Cloud review team on the
last OAUTH rounds. 

> Last week I also devoted some time to the "bureaucracy" behind all
> this and read everything on
> https://support.google.com/cloud/answer/9110914 (including all links
> and links in these links recursively if applicable) and I think I got
> the bigger picture. Some additional questions:
 
> 3. How to actually run oauth on iOS to make the video? Is there any nightly build with this capability turned on (to show e.g. the consent screen)? I could only find https://testflight.apple.com/join/uEMc1NxS but it doesn't seem to have it turned on nor allow one to simulate (open) the corresponding "consent" forms/panels/views/screens/whatever_its_called etc.

We have a gmail test account -- i think we asked them to allow it 
for OAUTH testing and they did.  

> 4. By "code-wise there is nothing missing" I suppose you meant it's 100% compliant with everything on https://developers.google.com/identity/protocols/oauth2/policies - or should I (or someone else who understands the codebase better) take a look before making the video and submitting the request for verification process?

Note that i think that iOS has no code yet to support the OAUTH flows client side. 
No code missing ... is probably more about the handling in the core -- 

@r10s can say some more words/suggestions on how to proceed. 
Note that if we go for iOS/OAUTH we also need to consider Desktop/OAUTH
and how things work with export/import. 

Note that we would regard Delta Chat Core as the sole client code that is 
interacting with GMail/OAUTH -- so we want to use the same client id on 
all platforms.  The alternative is needing a new client id (each of which
needs a review) per android/ios/desktop.  But this seems unneccessary 
overhead.  If you find anything about this in the Verification FAQ or other policy
documents please let us now.

thanks for sorting through this. Note that it's currently not our top
priority so the more help you and others can provide the more likely
this happens.  Also very grateful for @mmoya 's https://github.com/deltachat/deltachat-core-rust/pull/1626 PR which nicely extended the reach of DC/GMail support

**Comment by dumblob** [comment]
@hpk42 sent you an email with request for thread forwarding (you can verify it's me by running `printf the_canary_I_sent_you | md5sum` and comparing to `a221562a8342077fd5cf9bbe4d7b06f2`).

**Comment by r10s** [comment]
i am on some oauth2 things currently for other reasons (tweaking android wrt "G Suite domains" supported in the core now), so it seems to make sense for me to dive in here as well.

as a first step, i would try to get the existing code running, for testing, i can use some generic things google gave us. if this works out and we finally need a separate ios token, this is the moment, where it would be great if you can chime in @dumblob - and checkout out yandex before.

in theory, we could also support more oauth2 authorizers as yahoo and maybe others (outlook does not work at all nicely with delta), however, we just did not find the time to get into that.

**Comment by Gozala** [comment]
Lack of oauth support for gmail had being primary reason people tend to not get onboard with delta.chat in my experience, which is why I think having this can improve adoption.

**Comment by hpk42** [comment]
On Tue, Jul 14, 2020 at 23:23 -0700, Irakli Gozalishvili wrote:
> Lack of oauth support for gmail had being primary reason people tend to not get onboard with delta.chat in my experience, which is why I think having this can improve adoption.

FWIW recently @mmoya added support for GSuite domains in #1626
and if GMAIL/OAUTH would be available on iOS and Desktop, it could indeed be a very nice 
onboarding experience. However, this is likely considerable buereaucratic effort -- 
it easily took >50 hours to get Android/OAUTH to be accepted by the Google 
Cloud AUTH department.

**Comment by r10s** [comment]
i am currently on multi-account at #846, i think, as both affects onboarding, i will come over oauth2 parts, and can try to enable them and see what is actually working or what is needed code-wise.

**Comment by link2xt** [comment]
Recent forum thread with a request to (re-)add OAuth 2 support: https://support.delta.chat/t/cant-log-in-with-google-workspace-email/1921

**Comment by casey** [comment]
I'm the OP of the above thread. I'd really like this to happen, both because it's an issue I ran into, and because it's an issue that a huge number of potential users will run into, since both Gmail and iOS are extremely common. Can I make a donation or bounty earmarked towards getting this working? I don't know if that's something that the project does, but I figured it wouldn't hurt to ask.

**Comment by r10s** [comment]
moving  issue to [resurrection](https://github.com/orgs/deltachat/projects/19) due to [march2022 cleanup](https://github.com/orgs/deltachat/projects/48).
