### ISSUE TITLE
tweak date-line in bubbles

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#950]
- the date-line in the bubbles should be always right-aligned (this is true currently for outgoing messages, but not for incoming messages)

- the color of the outgoing messages date-line should be green (eg. #70b15c is used on android), in color of incoming messages date-line seems to be fine.

- the space between message and date-line is a bit too large, roughly the half should be fine.

**Comment by cyBerta** [comment]
the color in outgoing messages is only green in light mode. In dark mode it's a grey, because the background bubble is grey, too.

For compact layout (image only message), I think it's nicer to keep the color grey, as the background of the lable is grey, too.
![label_color](https://user-images.githubusercontent.com/2614900/96794237-221ed900-13fe-11eb-8e2c-17a3e1494330.png)
