### ISSUE TITLE
weird scrolling

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-ios#981]
i found a simple way to reproduce the weird scrolling behavior i mentioned in the a/v yesterday:

- open a chat with some more messages in, the chat opens correctly with the last message

- _without scrolling_, rotate the device from portrait to landscape mode

- the chat now jumps to somewhere up and scrolls immediately down to the last message again

if you rotate the device with the message list already scrolled up, this does not happen, things are fine and stable in this case.

i mentioned a similar behavior when entering more lines to the input field, might be that is the same issue, also there, the available height changes, however, this issue is harder to reproduce.

**Comment by cyBerta** [comment]
This is my understanding how rotation under iOS workds. 
Basically the rotation axis is the center cell of all loaded cells. They're called visible cells, but actually are not necessarily, there are some cells above the upper visible cells and some below the bottom visible cell that are taken into account too. 
Rotation works thus nicely without different offsets, if the table was scrolled up a bit and the cells have a similar size. At the bottom though rotating will case the table view to move up, because there are no cells that are loaded below the bottom cell and the rotation axis is thus higher. As a result, we need to manually scroll down after the rotation. We can do that either using an animation, which leads to strange scrolling or without which leads to snapping immediately back. I couldn't find a way for rotation without any visual hickup so far. 

Another bug, that leaded to jumping, and relates to the descibed behavior was fixed here: https://github.com/deltachat/deltachat-ios/pull/979/commits/b3423ebc64ba27142dc0ee343b8b1182363c2861 It's part of #979 
The inital rotation after entering the chat and without previous scrolling didn't cause a cell update for whatever reasons. A tableview.load() forces this now at the end of the rotation and only in case the table view was at the bottom before the rotation. Before that fix, you could enter a chat, rotate immediately, wait some time and see the cells changing their size, especially if you had an image at the bottom. The later cell update is caused by the timer that is used to update the sent dates in each cell.

**Comment by cyBerta** [comment]
I added another commit to #979 : https://github.com/deltachat/deltachat-ios/pull/979/commits/4de4c185aaa102d731d84c56d15cb57ec7120db7
