### ISSUE TITLE
[chatview] empty avatars

### ISSUE THREAD

**Issue by dignifiedquire** [deltachat/deltachat-ios#99]
Quite a lot of the avatars don't contain anything, or just a single letter now

**Comment by nayooti** [comment]
@dignifiedquire I reset recent changes in ChatView. Could you verify that the issue still exist in current version?

**Comment by nayooti** [comment]
if a text won't fit into a label iOS puts '...' by default.

I set the limit to 2 initials to avoid this. 

In case of a very long name it will only take the first letter now. 

If the badge is empty, I only had this once, it is because the Contact has no name assigned. Not sure how to prevent this, but names can always manually added.

I am going to (temporary) close this issue.
