### ISSUE TITLE
implement swipe-to-reply

### ISSUE THREAD

**Issue by cyBerta** [deltachat/deltachat-ios#993]
after implementing the UI to show quotes (#942) we should continue with providing UI to reply to messages. 
The swipe should be enabled on the left side of a chat message, just as in Android's swipe-to-reply feature.

**Comment by r10s** [comment]
this is roughly how i would see the quoting-area, together with the staging area:

<img width=350 src=https://user-images.githubusercontent.com/9800740/99416892-9e231880-28f9-11eb-858f-0abe6bb65e1b.png>


both areas should have some fixed height, so that there is enough space for keyboard. esp. the staging area should not be "huge" when attaching a portrait-size image - either the image should be cropped or be a bit smaller in preview. but we can figure out these details later.

**Comment by r10s** [comment]
closed by #995
